 version: '3'
 services:
  flask-backend:
   image: webapp-flask
   build:
    context: .
    dockerfile: Dockerfile-flask
   volumes:
    - "./:/app"
  nginx-frontend:
   image: webapp-nginx
   build:
    context: .
    dockerfile: Dockerfile-nginx
   ports:
    - 5000:80
   depends_on:
    - flask-backend
  node-angular:
    build:
     context: .
     dockerfile: Dockerfile-angular
    ports:
      - "80:4200"
    volumes:
      - ./Frontend/:/usr/src/app
    command: yarn run start

    